Reading package lists...
Building dependency tree...
Reading state information...
default-jdk is already the newest version (2:1.8-56ubuntu2).
default-jre is already the newest version (2:1.8-56ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 135 not upgraded.
